Feature/jwt authentication
open-rmf/rmf_visualization pull request #9
Opened 2021-04-09 07:34 UTC by ChawinTan

### Implemented feature

Feature Request: https://github.com/open-rmf/rmf-web/issues/277

Below is the library that I intend to use:
https://github.com/Thalhammer/jwt-cpp

This feature is to allow schedule visualizer's websocket server to verify jwt tokens from an external user and connect accept the connections only if the tokens are valid

### Implementation description

**Installing the library for testing purposes. This should be temporary**
1)`cd rmf_visualization/rmf_visualization_schedule`
2) `git clone https://github.com/Thalhammer/jwt-cpp.git`
3) `cd jwt-cpp` and then `mkdir out/build`
4) `cmake -S . -B out/build/` and then `make -C out/build` to build
5) `cd` into rmf_ws root folder
6) `colcon build --packages-select rmf_visualization_schedule` (after the latest name change)

Within the websocket server's `on_open` method, before it accepts a new user, it checks if an environmental variable that contains the public key, represented by `JWT_PUBLIC_KEY` exists. If it does not exist, it starts and accepts users as per normal. If it exist, then proceed to verify if a token is valid.

The client's url should include a `/?token=<jwt token> parameter which will be retrieved in this server for verification. If verification fails, an error message is thrown and client connection is refused.

2021-04-14 01:46 UTC, koonpeng requested changes
` if (url) this._backendWs = new WebSocket(url + '/?token=<your_token>')`
Do not put the token in the url, this is a security risk. See https://tools.ietf.org/html/rfc6750#page-6

```
   Because of the security weaknesses associated with the URI method
   (see Section 5), including the high likelihood that the URL
   containing the access token will be logged, it SHOULD NOT be used
   unless it is impossible to transport the access token in the
   "Authorization" request header field or the HTTP request entity-body.
   Resource servers MAY support this method.

   This method is included to document current use; its use is not
   recommended, due to its security deficiencies (see Section 5) and
   also because it uses a reserved query parameter name, which is
   counter to URI namespace best practices, per "Architecture of the
   World Wide Web, Volume One" [W3C.REC-webarch-20041215].
```

You choices are
1. Authorization header, can't use this because we can't send custom headers in a websocket request.
2. Cookies, beware of CSRF, ~to keep it safe, the cookie needs to be http-only. Since we dont control the auth server we can't exactly set this flag so the risk of CSRF is always present.~ http-only is to avoid XSS, avoiding CSRF is more complicated, one of the ways is to use a ephermal token, but we can't exactly do it with a websocket-only server.
3. Application level. Basically verify the token as part of the app, meaning to accept all connection, but lock all functionalities until the client sends a valid token.
4. Nonstandard websocket protocol. While you cannot set custom headers, one of the header you can set is the websocket protocol header ("Sec-protocol" or something similar). You can put the token in that header and the server will check it there.
5. Finally, the end-all solution would be to make a full-fledge oauth2 client. This means that you will register the app server to keycloak as a oauth2 client, the token is never exposed to the user agent, the app server will obtain the access token from the auth provider using the client_id and client_secret. The biggest challenge of this is that you need to have a session store, and possibly a database to persist said sessions, this is also probably the only way to properly implement option 2.

IMO option 3 or 4 would be the easiest.

2021-04-14 02:31 UTC, ChawinTan commented
Thanks for all the suggestions! 

For option 3, does that mean that the token would be send in the message payload itself and every request would have to be verified, similar to how the "role base" unlocking of features would work?

2021-04-14 09:50 UTC, ChawinTan commented
Realized that throwing an exception that causes the process to shut down is a bad idea. I introduced a boolean flag `is_verified` that controls the availability of the services depending on the verification outcome.

Refactored receive the jwt tokens on message payload rather than on connection.

Since we are passing the tokens in the message payload, how should we let the user know that the service is not available since the connection will still be going through? Should we create and send a message that informs them of the bad token or how is it normally done in such situations?

2021-04-15 08:17 UTC, koonpeng commented
> For option 3, does that mean that the token would be send in the message payload itself and every request would have to be verified, similar to how the "role base" unlocking of features would work?

Verifying per request is more secure, but I think you can look at socket.io and see how they do it. I think they only verify once on connection, I think this is more inline with how websockets typically works.

2021-04-15 15:40 UTC, ChawinTan commented
> Note that for verifying per request, there is a "bug" currently in the client in that it doesn't periodically refresh the token, so eventually you will get expired tokens.

What do you think of sending an error payload like the one below and when the client finds out that a token is expired, generates a new one? The error message is copied from the exception that is caught from the verifier. We can also get even more specific with the error messages when checking with parameters, eg `.with_issuer("auth0");`
![token_expired](https://user-images.githubusercontent.com/29136440/114896606-122f0180-9e43-11eb-9d69-b12fa3798b16.png)

I think this can be one of the TODOs as well, along with unifying the 2 separate websockets on the client and refactoring the client to handle cases where an error message is passed back.

For now though, the websocket server seems to be doing what I want it to do.

2021-04-16 04:48 UTC, koonpeng commented
The client knows when the token will expire so it can proactively refresh it without input from the server. The keycloak client has a function to refresh tokens, but I don't know if it is the access token or id token (or both). They may have different expriation, we are using the id token so we need to make sure that gets refreshed as well.

2021-04-21 02:54 UTC, ChawinTan commented
Design doc for the flow of the program:
![Jwt_authentication_design_doc](https://user-images.githubusercontent.com/29136440/115489760-5d0ba780-a28f-11eb-961f-04373756335f.png)

2021-04-22 11:51 UTC, koonpeng submitted a review, later dismissed
No objections with the code, but I would wait for the accompanying PR in rmf-web (refresh token pr) before merging this.

2021-04-22 11:51 UTC, koonpeng commented on .gitmodules
> +[submodule "rmf_visualization_schedule/jwt-cpp"]
looks like this points to a commit in master branch, I would recommend to use a release tag instead.

2021-04-23 01:31 UTC, koonpeng commented
> No objections with the code, but I would wait for the accompanying PR in rmf-web (refresh token pr) before merging this.

On 2nd thought, it doesn't matter as auth is disabled by default.

On a similar topic, does this support https or is there an example deployment enabling https? Because auth is useless without a secure connection.

2021-04-23 03:42 UTC, ChawinTan commented
> On a similar topic, does this support https or is there an example deployment enabling https? Because auth is useless without a secure connection.

Not that I know of. I don't think it supports TLS right now. Base on [this](https://github.com/zaphoyd/websocketpp/blob/0.6.0-permessage-deflate/examples/echo_server_tls/echo_server_tls.cpp) example, it seems like we need to use `asio_tls` instead of `asio` and potentially supporting both types.

2021-04-23 09:12 UTC, closed without merging